myblog_back/article/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from article import views



urlpatterns = [

    # 界面渲染:

    # 文章界面
    path('article/', views.article, name='article'),
    # 公告界面
    path('notice/', views.notice, name='notice'),
    # 评论界面
    path('comment/', views.comment, name='comment'),
    # 栏目界面
    path('category/',views.category, name='category'),
    # 友情链接界面
    path('flink/',views.flink, name='flink'),
    # 用户管理界面
    path('manage_user/',views.manage_user, name='manage_user'),
    # 登录日志界面
    path('loginlog/',views.loginlog, name='loginlog'),
    # 设置界面
    path('setting/',views.setting, name='setting'),
    # 阅读设置界面
    path('readset/',views.readset, name='readset'),



    # 功能如下:
    # 添加文章
    path('add_article/', views.add_article, name='add_article'),

    # 删除文章
    path('del_article/', views.del_article, name='del_article'),
    # 删除栏目
    path('del_category/', views.del_category, name='del_category'),
    # 更新文章
    path('update_article/<int:id>', views.update_article, name='update_article'),
    # 更新栏目
    path('update_category/<int:id>', views.update_category, name='update_category'),



]

# 声明路由对象
# router = SimpleRouter()
# # 定义资源
# router.register('category1', views.CateView)
# # 添加路由地址
# urlpatterns += router.urls

myblog_back/myblog_back/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import static

from myblog_back.settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    # 用户路由
    path('user/', include(('user.urls', 'user'), namespace='user')),
    # 文章路由
    path('article/', include(('article.urls', 'article'), namespace='article')),

]
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

if DEBUG:
    import debug_toolbar

    urlpatterns.append(re_path(r'^__debug__/', include(debug_toolbar.urls)))

myblog_back/user/urls.py
from django.urls import path

from user import views

urlpatterns=[
    # 登录校验
    path('login/', views.login, name='login'),
    path('index/', views.index, name='index'),

]

myblog_back/article/models.py
from django.db import models

# Create your models here.
# 文章分类表
class Category(models.Model):
    """
    文章分类
    """
    name = models.CharField(max_length=20,unique=True)
    nickname = models.CharField(max_length=20,default=None)
    high_category = models.ForeignKey('self',
                                 on_delete=models.CASCADE,
                                      related_name='hcate',)
    class Meta:
        db_table = 'category'

# 文章内容表
class Blog(models.Model):
    """
    博客文章表
    """
    title = models.CharField(max_length=100, unique=True)
    content = models.CharField(default='', max_length=9999)
    create_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    # 存图片的地址,数据库中icon字段的类型是varchar
    title_pic = models.ImageField(upload_to='upload',null=True)
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE,
                                 related_name='cate')

    class Meta:
        db_table = 'Blog'

myblog_back/article/views.py
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render


from django.urls import reverse
from rest_framework import viewsets, mixins
from rest_framework.response import Response

from article.form import  CateFrom
from article.models import Blog, Category

# 文章的方法:



def article(request):
    """
    文章界面
    :param request:
    :return:
    """
    if request.method == 'GET':
        blog_info = Blog.objects.all()

        page = int(request.GET.get('page',1))
        pg = Paginator(blog_info, 3)
        blog_info = pg.page(page)
        length = len(blog_info)

        return render(request, 'article.html', {'blog_info': blog_info,'length':length})


def comment(request):
    if request.method == 'GET':
        return render(request, 'comment.html')


def notice(request):
    """
    公告界面
    :param request:
    :return:
    """
    if request.method == 'GET':
        return render(request, 'notice.html')


def category(request):
    """
    栏目
    :param request:
    :return:
    """
    if request.method == 'GET':
        category = Category.objects.all()
        num = 0
        return render(request, 'category.html', {'category': category, 'num': num})
    if request.method == 'POST':
        form = CateFrom(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            nickname = form.cleaned_data['alias']
            fid = form.cleaned_data['fid']
            print(fid)
            c1 = Category.objects.filter(pk=fid).first()
            try:
                if nickname:
                    Category.objects.create(name=name,nickname=nickname,high_category=c1)
                else:
                    Category.objects.create(name=name,high_category=c1)
            except:
                pass
            return HttpResponseRedirect(reverse('article:category'))
        else:
            return render(request, 'category.html')

def flink(request):
    """
    友情链接
    :param request:
    :return:
    """
    if request.method == 'GET':
        return render(request, 'flink.html')

def manage_user(request):
    """
    用户管理
    :param request:
    :return:
    """
    if request.method == 'GET':
        return render(request, 'manage-user.html')

def loginlog(request):
    """
    登录日志
    :param request:
    :return:
    """
    if request.method == 'GET':
        return render(request, 'loginlog.html')

def setting(request):
    """
    用户设置
    :param request:
    :return:
    """
    if request.method == 'GET':
        return render(request, 'setting.html')

def readset(request):
    """
    阅读设置
    :param request:
    :return:
    """

    if request.method == 'GET':
        return render(request, 'readset.html')

def add_article(request):
    """
    添加文章
    :param request:
    :return:
    """
    if request.method == 'GET':
        category = Category.objects.all()
        return render(request, 'add-article.html', {'category':category})
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        new_category = request.POST.get('tags')
        nick_name = request.POST.get('alias')
        title_pic = request.FILES.get('titlepic')
        c_id = request.POST.get('category')
        c1 = Category.objects.filter(pk=c_id).first()
        if new_category:
            Category.objects.create(name=new_category,high_category=c1,nickname=nick_name)
            Blog.objects.create(title=title,
                                content=content,
                                title_pic=title_pic,
                                category=Category.objects.filter(name=new_category).first())
        else:
            Blog.objects.create(title=title,
                                content=content,
                                title_pic=title_pic,
                                category=c1)
        return HttpResponseRedirect(reverse('article:add_article'))

def del_category(request):
    """
    删除指定栏目
    :param request:
    :return:
    """
    if request.method == 'POST':
        cate_id = request.POST.get('cate_id')
        Category.objects.filter(pk=cate_id).delete()
        cate = Category.objects.filter(pk=cate_id).first()
        Category.objects.filter(high_category=cate).delete()
        return JsonResponse({'code':'200','msg':'请求成功'})
def update_category(request, id):
    """
    更新栏目
    :param request:
    :return:
    """
    if request.method == 'GET':
        category = Category.objects.filter(pk=id).first()
        all_category = Category.objects.all()
        return render(request,'update-category.html',{'category':category,'all_category':all_category})
    if request.method == 'POST':
        form = CateFrom(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            nickname = form.cleaned_data['alias']
            fid = form.cleaned_data['fid']
            c1 = Category.objects.filter(pk=fid).first()

            cate = Category.objects.filter(pk=id).first()
            cate.name = name
            cate.nickname = nickname
            cate.high_category = c1
            cate.save()
            return HttpResponseRedirect(reverse('article:category'))
        else:
            return HttpResponseRedirect(reverse('article:category'))

# class CateView(viewsets.GenericViewSet,
#                mixins.ListModelMixin,
#                mixins.RetrieveModelMixin,
#                mixins.CreateModelMixin,
#                mixins.UpdateModelMixin,
#                mixins.DestroyModelMixin):
#     queryset = Category.objects.all()
#     serializer_class = CateSerializer

def del_article(request):
    """
    删除文章
    :param request:
    :return:
    """
    if request.method == 'POST':
        blog_id = request.POST.get('blog_id')
        Blog.objects.filter(pk=blog_id).delete()

        return JsonResponse({'code':200,'msg':'请求成功'})

def update_article(request, id):
    """
    更新文章
    :param request:
    :param id:
    :return:
    """
    if request.method == 'GET':
        category = Category.objects.all()
        blog = Blog.objects.filter(pk=id).first()
        return render(request, 'update-article.html', {'category':category, 'blog':blog})
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        title_pic = request.FILES.get('titlepic')
        c_id = request.POST.get('category')

        c1 = Category.objects.filter(pk=c_id).first()
        blogs = Blog.objects.filter(pk=id).first()

        blogs.title = title
        blogs.content = content
        blogs.category = c1
        blogs.title_pic=title_pic
        blogs.save()
        return HttpResponseRedirect(reverse('article:article'))

myblog_back/templates/add-category.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>无标题文档</title>
</head>

<body>
</body>
</html>

myblog_back/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>异清轩博客管理系统</title>
    {% block css %}
    {% endblock %}

    {% block js1 %}
    {% endblock %}
</head>
<body class="user-select">
    {% block content %}
    {% endblock %}


    {% block js2 %}
    {% endblock %}
</body>
</html>

myblog_back/templates/base_main.html
{% extends 'base.html' %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">
    <link rel="apple-touch-icon-precomposed" href="/static/images/icon/icon.png">
    <link rel="shortcut icon" href="/static/images/icon/favicon.ico">
{% endblock %}

{% block js1 %}
    <script src="/static/js/jquery-2.1.4.min.js"></script>
    <script src="/static/js/jquery-1.11.1.min.js" type="text/javascript"></script>
    <script src="/static/js/html5shiv.min.js" type="text/javascript"></script>
    <script src="/static/js/respond.min.js" type="text/javascript"></script>
    <script src="/static/js/selectivizr-min.js" type="text/javascript"></script>

{% endblock %}

{% block content %}


{% endblock %}

myblog_back/templates/category.html
{% extends 'base_main.html' %}


{% block content %}
<section class="container-fluid">
  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="/">YlsatCMS</a> </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="">消息 <span class="badge">1</span></a></li>
            <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">admin <span class="caret"></span></a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><a title="查看或修改个人信息" data-toggle="modal" data-target="#seeUserInfo">个人信息</a></li>
                <li><a title="查看您的登录记录" data-toggle="modal" data-target="#seeUserLoginlog">登录记录</a></li>
              </ul>
            </li>
            <li><a href="login.html" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
            <li><a data-toggle="modal" data-target="#WeChat">帮助</a></li>
          </ul>
          <form action="" method="post" class="navbar-form navbar-right" role="search">
            {% csrf_token %}
            <div class="input-group">
              <input type="text" class="form-control" autocomplete="off" placeholder="键入关键字搜索" maxlength="15">
              <span class="input-group-btn">
              <button class="btn btn-default" type="submit">搜索</button>
              </span> </div>
          </form>
        </div>
      </div>
    </nav>
  </header>
  <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li class="active"><a href="{% url 'user:index' %}">报告</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'article:article' %}">文章</a></li>
        <li><a href="{% url 'article:notice' %}">公告</a></li>
        <li><a href="{% url 'article:comment' %}">评论</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'article:category' %}">栏目</a></li>
        <li><a class="dropdown-toggle" id="otherMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">其他</a>
          <ul class="dropdown-menu" aria-labelledby="otherMenu">
            <li><a href="{% url 'article:flink' %}">友情链接</a></li>
            <li><a data-toggle="modal" data-target="#areDeveloping">访问记录</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a class="dropdown-toggle" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">用户</a>
          <ul class="dropdown-menu" aria-labelledby="userMenu">
            <li><a data-toggle="modal" data-target="#areDeveloping">管理用户组</a></li>
            <li><a href="{% url 'article:manage_user' %}">管理用户</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'article:loginlog' %}">管理登录日志</a></li>
          </ul>
        </li>
        <li><a class="dropdown-toggle" id="settingMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">设置</a>
          <ul class="dropdown-menu" aria-labelledby="settingMenu">
            <li><a href="{% url 'article:setting' %}">基本设置</a></li>
            <li><a href="{% url 'article:readset' %}">阅读设置</a></li>
            <li role="separator" class="divider"></li>
            <li><a data-toggle="modal" data-target="#areDeveloping">安全配置</a></li>
            <li role="separator" class="divider"></li>
            <li class="disabled"><a>扩展菜单</a></li>
          </ul>
        </li>
      </ul>
    </aside>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <div class="row">
        <div class="col-md-5">
          <h1 class="page-header">添加</h1>
          <form action="" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="form-group">
              <label for="category-name">栏目名称</label>
              <input type="text" id="category-name" name="name" class="form-control" placeholder="在此处输入栏目名称" required autocomplete="off">
              <span class="prompt-text">这将是它在站点上显示的名字。</span> </div>
            <div class="form-group">
              <label for="category-alias">栏目别名</label>
              <input type="text" id="category-alias" name="alias" class="form-control" placeholder="在此处输入栏目别名" required autocomplete="off">
              <span class="prompt-text">“别名”是在URL中使用的别称，它可以令URL更美观。通常使用小写，只能包含字母，数字和连字符（-）。</span> </div>
            <div class="form-group">
              <label for="category-fname">父节点</label>
              <select id="category-fname" class="form-control" name="fid">
                {% for cate in category %}
                <option value= "{{ cate.id }}">{{ cate.name }}</option>
                {% endfor %}
              </select>
              <span class="prompt-text">栏目是有层级关系的，您可以有一个“音乐”分类目录，在这个目录下可以有叫做“流行”和“古典”的子目录。</span> </div>
            <button class="btn btn-primary" type="submit" name="submit">添加新栏目</button>
          </form>
        </div>
        <div class="col-md-7">
          <h1 class="page-header">管理 <span class="badge">3</span></h1>
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th><span class="glyphicon glyphicon-paperclip"></span> <span class="visible-lg">ID</span></th>
                  <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">名称</span></th>
                  <th><span class="glyphicon glyphicon-list-alt"></span> <span class="visible-lg">别名</span></th>
                  <th><span class="glyphicon glyphicon-pushpin"></span> <span class="visible-lg">总数</span></th>
                  <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
                </tr>
              </thead>
              <tbody>
                {% for cate in category %}
                <tr>
                  <td>{{ cate.id }}</td>
                  <td>{{ cate.name }}</td>
                  <td {% if cate.nickname %}>{{ cate.nickname}}</td>
                  <td {% else %}>无</td>
                  {% endif %}
                  <td>125</td>
                  <td><a href="{% url  'article:update_category' cate.id %}">修改</a> <a  rel="" onclick="del_category({{ cate.id }})" >删除</a></td>
                </tr>
                {% endfor %}
                <script>
                 function del_category(id){
                    var csrf = $('input[name="csrfmiddlewaretoken"]').val()
                    $.ajax({
                        	url:'/article/del_category/',
                        	type:'POST',
							data: {'cate_id':id},
							headers:{'X-CSRFToken': csrf},
							dataType:'json',
							success: function(data){
								if(data.code == '200'){
                                    window.location.reload()
									}
							},
							error: function(data){
							}
						})
					}

                </script>
              </tbody>
            </table>
            <span class="prompt-text"><strong>注：</strong>删除一个栏目也会删除栏目下的文章和子栏目,请谨慎删除!</span> </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--个人信息模态框-->
<div class="modal fade" id="seeUserInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <form action="" method="post">
      {% csrf_token %}
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" >个人信息</h4>
        </div>
        <div class="modal-body">
          <table class="table" style="margin-bottom:0px;">
            <thead>
              <tr> </tr>
            </thead>
            <tbody>
              <tr>
                <td wdith="20%">姓名:</td>
                <td width="80%"><input type="text" value="王雨" class="form-control" name="truename" maxlength="10" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">用户名:</td>
                <td width="80%"><input type="text" value="admin" class="form-control" name="username" maxlength="10" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">电话:</td>
                <td width="80%"><input type="text" value="18538078281" class="form-control" name="usertel" maxlength="13" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">旧密码:</td>
                <td width="80%"><input type="password" class="form-control" name="old_password" maxlength="18" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">新密码:</td>
                <td width="80%"><input type="password" class="form-control" name="password" maxlength="18" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">确认密码:</td>
                <td width="80%"><input type="password" class="form-control" name="new_password" maxlength="18" autocomplete="off" /></td>
              </tr>
            </tbody>
            <tfoot>
              <tr></tr>
            </tfoot>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
          <button type="submit" class="btn btn-primary">提交</button>
        </div>
      </div>
    </form>
  </div>
</div>
<!--个人登录记录模态框-->
<div class="modal fade" id="seeUserLoginlog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" >登录记录</h4>
      </div>
      <div class="modal-body">
        <table class="table" style="margin-bottom:0px;">
          <thead>
            <tr>
              <th>登录IP</th>
              <th>登录时间</th>
              <th>状态</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>::1:55570</td>
              <td>2016-01-08 15:50:28</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:64377</td>
              <td>2016-01-08 10:27:44</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:64027</td>
              <td>2016-01-08 10:19:25</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:57081</td>
              <td>2016-01-06 10:35:12</td>
              <td>成功</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">朕已阅</button>
      </div>
    </div>
  </div>
</div>
<!--微信二维码模态框-->
<div class="modal fade user-select" id="WeChat" tabindex="-1" role="dialog" aria-labelledby="WeChatModalLabel">
  <div class="modal-dialog" role="document" style="margin-top:120px;max-width:280px;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="WeChatModalLabel" style="cursor:default;">微信扫一扫</h4>
      </div>
      <div class="modal-body" style="text-align:center"> <img src="images/weixin.jpg" alt="" style="cursor:pointer"/> </div>
    </div>
  </div>
</div>
<!--提示模态框-->
<div class="modal fade user-select" id="areDeveloping" tabindex="-1" role="dialog" aria-labelledby="areDevelopingModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="areDevelopingModalLabel" style="cursor:default;">该功能正在日以继夜的开发中…</h4>
      </div>
      <div class="modal-body"> <img src="images/baoman/baoman_01.gif" alt="深思熟虑" />
        <p style="padding:15px 15px 15px 100px; position:absolute; top:15px; cursor:default;">很抱歉，程序猿正在日以继夜的开发此功能，本程序将会在以后的版本中持续完善！</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">朕已阅</button>
      </div>
    </div>
  </div>
</div>
<!--右键菜单列表-->
<div id="rightClickMenu">
  <ul class="list-group rightClickMenuList">
    <li class="list-group-item disabled">欢迎访问异清轩博客</li>
    <li class="list-group-item"><span>IP：</span>172.16.10.129</li>
    <li class="list-group-item"><span>地址：</span>河南省郑州市</li>
    <li class="list-group-item"><span>系统：</span>Windows10 </li>
    <li class="list-group-item"><span>浏览器：</span>Chrome47</li>
  </ul>
</div>
{% endblock %}

{% block js2%}
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/admin-scripts.js"></script>

{% endblock %}